springdoc:
  # Spring Framework 버전 호환 이슈로 ControllerAdvice 스캔 과정에서 500이 나서 비활성화
  override-with-generic-response: false


app:
  jwt:
    secret: "0uiyTBbnRmVw8wm0hSz5eoZ4vt7LCpnuRroC2bmdt9Q="
    issuer: "ticket-app"
    expires-minutes: 60