spring:
  datasource:
    url: jdbc:postgresql://db:5432/ticketdb
    username: ticket
    password: ticketpw

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
#    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false
#    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.jdbc.bind: trace
    org.flywaydb: debug
    org.springframework.boot.autoconfigure.flyway: debug

debug: true