services:
  db:
    image: postgres:16
    container_name: ticket-postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticketpw
    ports:
      - "5432:5432"
    volumes:
      - ticket_pg_data:/var/lib/postgresql/data
volumes:
  ticket_pg_data: